[project]
name = "unsloth-llama31-lora"
version = "0.1.0"
description = "Fine tune Llama 3.1 8B with Unsloth and save LoRA adapters"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[tool.black]
line-length = 100

[tool.isort]
profile = "black"
